/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 16.1.0
board: FRDM-MCXN947
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 06463824-f3aa-40a8-9e9a-9ba355d40582
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FLEXIO0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXIO0'
- type: 'flexio_reg'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'flexio_reg'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXIO0'
- config_sets:
  - generalConfig:
    - clkConfig:
      - clockSource: 'FlexIoClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - flexioConfig:
      - FLEXEN: 'true'
      - FASTACC: 'false'
      - DBGE: 'true'
      - DOZEN: 'true'
      - STATE: '1721113475092'
    - tabs:
      - timers_tab:
        - timers:
          - 0:
            - uid: '1721113475085'
            - id: 'TIMER0'
            - number: '0'
            - description: ''
            - TIMOD: '3'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1TIMER'
            - TRGSEL: '1721113475070'
            - TRGPOL: '0'
            - PINSEL: '24'
            - PINCFG: '3'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '6'
            - TIMDIS: '6'
            - TIMRST: '0'
            - TIMOUT: '1'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '49'
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
          - 1:
            - uid: '1721113475066'
            - id: 'TIMER1'
            - number: '1'
            - description: ''
            - TIMOD: '3'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1PIN'
            - TRGSEL: '1'
            - TRGPOL: '1'
            - PINSEL: '25'
            - PINCFG: '3'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '6'
            - TIMDIS: '6'
            - TIMRST: '0'
            - TIMOUT: '1'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '4'
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
          - 2:
            - uid: '1721113475067'
            - id: 'TIMER2'
            - number: '2'
            - description: ''
            - TIMOD: '3'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1TIMER'
            - TRGSEL: '1721113475070'
            - TRGPOL: '1'
            - PINSEL: '26'
            - PINCFG: '3'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '6'
            - TIMDIS: '6'
            - TIMRST: '0'
            - TIMOUT: '1'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '149'
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
          - 3:
            - uid: '1721113475069'
            - id: 'TIMER3'
            - number: '3'
            - description: ''
            - TIMOD: '3'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1PIN'
            - TRGSEL: '0'
            - TRGPOL: '1'
            - PINSEL: '27'
            - PINCFG: '3'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '6'
            - TIMDIS: '6'
            - TIMRST: '0'
            - TIMOUT: '1'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '4'
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
          - 4:
            - uid: '1721113475070'
            - id: 'TIMER4'
            - number: '4'
            - description: ''
            - TIMOD: '3'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '0'
            - TRGSEL: '0'
            - TRGPOL: '0'
            - PINSEL: '28'
            - PINCFG: '3'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '0'
            - TIMDIS: '0'
            - TIMRST: '0'
            - TIMOUT: '0'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '199'
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
      - shifters_tab:
        - shifters:
          - 0:
            - uid: '1721113475092'
            - id: 'SHIFTER0'
            - number: '0'
            - description: 'S0'
            - SMOD: '6'
            - SSIZE: '0'
            - LATST: '0'
            - TIMSEL: '1721113475085'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '16'
            - PINCFG: '3'
            - PINPOL: '0'
            - statesShifter:
              - 0:
                - shifterStateSel_t: '1721113475077'
              - 1:
                - shifterStateSel_t: '1721113475092'
              - 2:
                - shifterStateSel_t: '1721113475092'
              - 3:
                - shifterStateSel_t: '1721113475092'
              - 4:
                - shifterStateSel_t: '1721113475092'
              - 5:
                - shifterStateSel_t: '1721113475092'
              - 6:
                - shifterStateSel_t: '1721113475092'
              - 7:
                - shifterStateSel_t: '1721113475092'
            - pinOutputStateMask:
              - 0:
                - pinMask_t: '0'
                - outputState: '0'
              - 1:
                - pinMask_t: '0'
                - outputState: '1'
              - 2:
                - pinMask_t: '1'
                - outputState: '0'
              - 3:
                - pinMask_t: '1'
                - outputState: '0'
              - 4:
                - pinMask_t: '1'
                - outputState: '0'
              - 5:
                - pinMask_t: '1'
                - outputState: '0'
              - 6:
                - pinMask_t: '1'
                - outputState: '0'
              - 7:
                - pinMask_t: '1'
                - outputState: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 1:
            - uid: '1721113475077'
            - id: 'SHIFTER1'
            - number: '1'
            - description: 'S1'
            - SMOD: '6'
            - SSIZE: '0'
            - LATST: '0'
            - TIMSEL: '1721113475066'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '16'
            - PINCFG: '3'
            - PINPOL: '0'
            - statesShifter:
              - 0:
                - shifterStateSel_t: '1721113475081'
              - 1:
                - shifterStateSel_t: '1721113475092'
              - 2:
                - shifterStateSel_t: '1721113475092'
              - 3:
                - shifterStateSel_t: '1721113475092'
              - 4:
                - shifterStateSel_t: '1721113475092'
              - 5:
                - shifterStateSel_t: '1721113475092'
              - 6:
                - shifterStateSel_t: '1721113475092'
              - 7:
                - shifterStateSel_t: '1721113475092'
            - pinOutputStateMask:
              - 0:
                - pinMask_t: '0'
                - outputState: '0'
              - 1:
                - pinMask_t: '0'
                - outputState: '0'
              - 2:
                - pinMask_t: '1'
                - outputState: '0'
              - 3:
                - pinMask_t: '1'
                - outputState: '0'
              - 4:
                - pinMask_t: '1'
                - outputState: '0'
              - 5:
                - pinMask_t: '1'
                - outputState: '0'
              - 6:
                - pinMask_t: '1'
                - outputState: '0'
              - 7:
                - pinMask_t: '1'
                - outputState: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 2:
            - uid: '1721113475081'
            - id: 'SHIFTER2'
            - number: '2'
            - description: 'S2'
            - SMOD: '6'
            - SSIZE: '0'
            - LATST: '0'
            - TIMSEL: '1721113475067'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '16'
            - PINCFG: '3'
            - PINPOL: '0'
            - statesShifter:
              - 0:
                - shifterStateSel_t: '1721113475091'
              - 1:
                - shifterStateSel_t: '1721113475092'
              - 2:
                - shifterStateSel_t: '1721113475092'
              - 3:
                - shifterStateSel_t: '1721113475092'
              - 4:
                - shifterStateSel_t: '1721113475092'
              - 5:
                - shifterStateSel_t: '1721113475092'
              - 6:
                - shifterStateSel_t: '1721113475092'
              - 7:
                - shifterStateSel_t: '1721113475092'
            - pinOutputStateMask:
              - 0:
                - pinMask_t: '0'
                - outputState: '1'
              - 1:
                - pinMask_t: '0'
                - outputState: '0'
              - 2:
                - pinMask_t: '1'
                - outputState: '0'
              - 3:
                - pinMask_t: '1'
                - outputState: '0'
              - 4:
                - pinMask_t: '1'
                - outputState: '0'
              - 5:
                - pinMask_t: '1'
                - outputState: '0'
              - 6:
                - pinMask_t: '1'
                - outputState: '0'
              - 7:
                - pinMask_t: '1'
                - outputState: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 3:
            - uid: '1721113475091'
            - id: 'SHIFTER3'
            - number: '3'
            - description: 'SL_0'
            - SMOD: '6'
            - SSIZE: '0'
            - LATST: '0'
            - TIMSEL: '1721113475069'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '16'
            - PINCFG: '3'
            - PINPOL: '0'
            - statesShifter:
              - 0:
                - shifterStateSel_t: '1721113475087'
              - 1:
                - shifterStateSel_t: '1721113475092'
              - 2:
                - shifterStateSel_t: '1721113475092'
              - 3:
                - shifterStateSel_t: '1721113475092'
              - 4:
                - shifterStateSel_t: '1721113475092'
              - 5:
                - shifterStateSel_t: '1721113475092'
              - 6:
                - shifterStateSel_t: '1721113475092'
              - 7:
                - shifterStateSel_t: '1721113475092'
            - pinOutputStateMask:
              - 0:
                - pinMask_t: '0'
                - outputState: '0'
              - 1:
                - pinMask_t: '0'
                - outputState: '0'
              - 2:
                - pinMask_t: '1'
                - outputState: '0'
              - 3:
                - pinMask_t: '1'
                - outputState: '0'
              - 4:
                - pinMask_t: '1'
                - outputState: '0'
              - 5:
                - pinMask_t: '1'
                - outputState: '0'
              - 6:
                - pinMask_t: '1'
                - outputState: '0'
              - 7:
                - pinMask_t: '1'
                - outputState: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 4:
            - uid: '1721113475087'
            - id: 'SHIFTER4'
            - number: '4'
            - description: 'S4'
            - SMOD: '6'
            - SSIZE: '0'
            - LATST: '0'
            - TIMSEL: '1721113475070'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '16'
            - PINCFG: '3'
            - PINPOL: '0'
            - statesShifter:
              - 0:
                - shifterStateSel_t: '1721113475092'
              - 1:
                - shifterStateSel_t: '1721113475092'
              - 2:
                - shifterStateSel_t: '1721113475092'
              - 3:
                - shifterStateSel_t: '1721113475092'
              - 4:
                - shifterStateSel_t: '1721113475092'
              - 5:
                - shifterStateSel_t: '1721113475092'
              - 6:
                - shifterStateSel_t: '1721113475092'
              - 7:
                - shifterStateSel_t: '1721113475092'
            - pinOutputStateMask:
              - 0:
                - pinMask_t: '0'
                - outputState: '0'
              - 1:
                - pinMask_t: '0'
                - outputState: '1'
              - 2:
                - pinMask_t: '1'
                - outputState: '0'
              - 3:
                - pinMask_t: '1'
                - outputState: '0'
              - 4:
                - pinMask_t: '1'
                - outputState: '0'
              - 5:
                - pinMask_t: '1'
                - outputState: '0'
              - 6:
                - pinMask_t: '1'
                - outputState: '0'
              - 7:
                - pinMask_t: '1'
                - outputState: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
      - pins_overview:
        - 0:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 1:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 2:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 3:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 4:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 5:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 6:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 7:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 8:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 9:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 10:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 11:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 12:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 13:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 14:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 15:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 16:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 17:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 18:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 19:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 20:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 21:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 22:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 23:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 24:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 25:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 26:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 27:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 28:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 29:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 30:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 31:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
      - external_trigger_IRQ:
        - 0:
          - TRIE: 'false'
        - 1:
          - TRIE: 'false'
        - 2:
          - TRIE: 'false'
        - 3:
          - TRIE: 'false'
        - 4:
          - TRIE: 'false'
        - 5:
          - TRIE: 'false'
        - 6:
          - TRIE: 'false'
        - 7:
          - TRIE: 'false'
    - enable_interrupt: 'false'
    - interrupt:
      - IRQn: 'FLEXIO_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - flexio_params: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void FLEXIO0_init(void) {
  /* Software reset of the FLEXIO0 peripheral. */
  SYSCON0->PRESETCTRL2 |= SYSCON_PRESETCTRL2_FLEXIO_RST_MASK;
  SYSCON0->PRESETCTRL2 &= ~SYSCON_PRESETCTRL2_FLEXIO_RST_MASK;
  /* FlexIO initialization */
  /* Control register initialization, set software reset bit then clear it */
  FLEXIO0->CTRL |= FLEXIO_CTRL_SWRST_MASK;
  FLEXIO0->CTRL &= ~FLEXIO_CTRL_SWRST_MASK;

  /* Write 1 to clear all shifter status */
  FLEXIO0->SHIFTSTAT = 0xFFFFFFFFU;

  /* Write 1 to clear all shifter error */
  FLEXIO0->SHIFTERR = 0xFFFFFFFFU;

  /* Write 1 to clear all timer status */
  FLEXIO0->TIMSTAT = 0xFFFFFFFFU;

#ifdef FLEXIO_TRGSTAT_ETSF_MASK
  /* Write 1 to clear all external trigger status */
  FLEXIO0->TRGSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_TRGSTAT_ETSF_MASK */

#ifdef FLEXIO_PINSTAT_PSF_MASK
  /* Write 1 to clear all pin status */
  FLEXIO0->PINSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_PINSTAT_PSF_MASK */

  /* FlexIO shifter 0 initialization */
  /* Shifter buffer register SHIFTBUFn initialization */
#ifdef FLEXIO0_SHIFTBUF0_INIT
  FLEXIO0->SHIFTBUF[0] = FLEXIO0_SHIFTBUF0_INIT;
#endif /* FLEXIO0_SHIFTBUF0_INIT */

  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG0_INIT
  FLEXIO0->SHIFTCFG[0] = FLEXIO0_SHIFTCFG0_INIT;
#else
  FLEXIO0->SHIFTCFG[0] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG0_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL0_INIT
  FLEXIO0->SHIFTCTL[0] = FLEXIO0_SHIFTCTL0_INIT;
#else
  FLEXIO0->SHIFTCTL[0] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL0_INIT */

  /* FlexIO shifter 1 initialization */
  /* Shifter buffer register SHIFTBUFn initialization */
#ifdef FLEXIO0_SHIFTBUF1_INIT
  FLEXIO0->SHIFTBUF[1] = FLEXIO0_SHIFTBUF1_INIT;
#endif /* FLEXIO0_SHIFTBUF1_INIT */

  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG1_INIT
  FLEXIO0->SHIFTCFG[1] = FLEXIO0_SHIFTCFG1_INIT;
#else
  FLEXIO0->SHIFTCFG[1] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG1_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL1_INIT
  FLEXIO0->SHIFTCTL[1] = FLEXIO0_SHIFTCTL1_INIT;
#else
  FLEXIO0->SHIFTCTL[1] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL1_INIT */

  /* FlexIO shifter 2 initialization */
  /* Shifter buffer register SHIFTBUFn initialization */
#ifdef FLEXIO0_SHIFTBUF2_INIT
  FLEXIO0->SHIFTBUF[2] = FLEXIO0_SHIFTBUF2_INIT;
#endif /* FLEXIO0_SHIFTBUF2_INIT */

  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG2_INIT
  FLEXIO0->SHIFTCFG[2] = FLEXIO0_SHIFTCFG2_INIT;
#else
  FLEXIO0->SHIFTCFG[2] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG2_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL2_INIT
  FLEXIO0->SHIFTCTL[2] = FLEXIO0_SHIFTCTL2_INIT;
#else
  FLEXIO0->SHIFTCTL[2] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL2_INIT */

  /* FlexIO shifter 3 initialization */
  /* Shifter buffer register SHIFTBUFn initialization */
#ifdef FLEXIO0_SHIFTBUF3_INIT
  FLEXIO0->SHIFTBUF[3] = FLEXIO0_SHIFTBUF3_INIT;
#endif /* FLEXIO0_SHIFTBUF3_INIT */

  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG3_INIT
  FLEXIO0->SHIFTCFG[3] = FLEXIO0_SHIFTCFG3_INIT;
#else
  FLEXIO0->SHIFTCFG[3] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG3_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL3_INIT
  FLEXIO0->SHIFTCTL[3] = FLEXIO0_SHIFTCTL3_INIT;
#else
  FLEXIO0->SHIFTCTL[3] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL3_INIT */

  /* FlexIO shifter 4 initialization */
  /* Shifter buffer register SHIFTBUFn initialization */
#ifdef FLEXIO0_SHIFTBUF4_INIT
  FLEXIO0->SHIFTBUF[4] = FLEXIO0_SHIFTBUF4_INIT;
#endif /* FLEXIO0_SHIFTBUF4_INIT */

  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG4_INIT
  FLEXIO0->SHIFTCFG[4] = FLEXIO0_SHIFTCFG4_INIT;
#else
  FLEXIO0->SHIFTCFG[4] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG4_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL4_INIT
  FLEXIO0->SHIFTCTL[4] = FLEXIO0_SHIFTCTL4_INIT;
#else
  FLEXIO0->SHIFTCTL[4] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL4_INIT */

  /* FlexIO timer 0 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL0_INIT
  FLEXIO0->TIMCTL[0] = FLEXIO0_TIMCTL0_INIT;
#else
  FLEXIO0->TIMCTL[0] = 0x0U;
#endif /* FLEXIO0_TIMCTL0_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG0_INIT
  FLEXIO0->TIMCFG[0] = FLEXIO0_TIMCFG0_INIT;
#else
  FLEXIO0->TIMCFG[0] = 0x0U;
#endif /* FLEXIO0_TIMCFG0_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP0_INIT
  FLEXIO0->TIMCMP[0] = FLEXIO0_TIMCMP0_INIT;
#else
  FLEXIO0->TIMCMP[0] = 0x0U;
#endif /* FLEXIO0_TIMCMP0_INIT */

  /* FlexIO timer 1 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL1_INIT
  FLEXIO0->TIMCTL[1] = FLEXIO0_TIMCTL1_INIT;
#else
  FLEXIO0->TIMCTL[1] = 0x0U;
#endif /* FLEXIO0_TIMCTL1_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG1_INIT
  FLEXIO0->TIMCFG[1] = FLEXIO0_TIMCFG1_INIT;
#else
  FLEXIO0->TIMCFG[1] = 0x0U;
#endif /* FLEXIO0_TIMCFG1_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP1_INIT
  FLEXIO0->TIMCMP[1] = FLEXIO0_TIMCMP1_INIT;
#else
  FLEXIO0->TIMCMP[1] = 0x0U;
#endif /* FLEXIO0_TIMCMP1_INIT */

  /* FlexIO timer 2 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL2_INIT
  FLEXIO0->TIMCTL[2] = FLEXIO0_TIMCTL2_INIT;
#else
  FLEXIO0->TIMCTL[2] = 0x0U;
#endif /* FLEXIO0_TIMCTL2_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG2_INIT
  FLEXIO0->TIMCFG[2] = FLEXIO0_TIMCFG2_INIT;
#else
  FLEXIO0->TIMCFG[2] = 0x0U;
#endif /* FLEXIO0_TIMCFG2_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP2_INIT
  FLEXIO0->TIMCMP[2] = FLEXIO0_TIMCMP2_INIT;
#else
  FLEXIO0->TIMCMP[2] = 0x0U;
#endif /* FLEXIO0_TIMCMP2_INIT */

  /* FlexIO timer 3 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL3_INIT
  FLEXIO0->TIMCTL[3] = FLEXIO0_TIMCTL3_INIT;
#else
  FLEXIO0->TIMCTL[3] = 0x0U;
#endif /* FLEXIO0_TIMCTL3_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG3_INIT
  FLEXIO0->TIMCFG[3] = FLEXIO0_TIMCFG3_INIT;
#else
  FLEXIO0->TIMCFG[3] = 0x0U;
#endif /* FLEXIO0_TIMCFG3_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP3_INIT
  FLEXIO0->TIMCMP[3] = FLEXIO0_TIMCMP3_INIT;
#else
  FLEXIO0->TIMCMP[3] = 0x0U;
#endif /* FLEXIO0_TIMCMP3_INIT */

  /* FlexIO timer 4 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL4_INIT
  FLEXIO0->TIMCTL[4] = FLEXIO0_TIMCTL4_INIT;
#else
  FLEXIO0->TIMCTL[4] = 0x0U;
#endif /* FLEXIO0_TIMCTL4_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG4_INIT
  FLEXIO0->TIMCFG[4] = FLEXIO0_TIMCFG4_INIT;
#else
  FLEXIO0->TIMCFG[4] = 0x0U;
#endif /* FLEXIO0_TIMCFG4_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP4_INIT
  FLEXIO0->TIMCMP[4] = FLEXIO0_TIMCMP4_INIT;
#else
  FLEXIO0->TIMCMP[4] = 0x0U;
#endif /* FLEXIO0_TIMCMP4_INIT */

  /* Shifter status interrupt register initialization */
#ifdef FLEXIO0_SHIFTSIEN_INIT
  FLEXIO0->SHIFTSIEN = FLEXIO0_SHIFTSIEN_INIT;
#else
  FLEXIO0->SHIFTSIEN = 0x0U;
#endif /* FLEXIO0_SHIFTSIEN_INIT */

  /* Shifter error interrupt register initialization */
#ifdef FLEXIO0_SHIFTEIEN_INIT
  FLEXIO0->SHIFTEIEN = FLEXIO0_SHIFTEIEN_INIT;
#else
  FLEXIO0->SHIFTEIEN = 0x0U;
#endif /* FLEXIO0_SHIFTEIEN_INIT */

  /* Timer interrupt register initialization */
#ifdef FLEXIO0_TIMIEN_INIT
  FLEXIO0->TIMIEN = FLEXIO0_TIMIEN_INIT;
#else
  FLEXIO0->TIMIEN = 0x0U;
#endif /* FLEXIO0_TIMIEN_INIT */

  /* Shifter status DMA register initialization */
#ifdef FLEXIO0_SHIFTSDEN_INIT
  FLEXIO0->SHIFTSDEN = FLEXIO0_SHIFTSDEN_INIT;
#else
  FLEXIO0->SHIFTSDEN = 0x0U;
#endif /* FLEXIO0_SHIFTSDEN_INIT */

#ifdef FLEXIO_TIMERSDEN_TSDE_MASK
  /* Timer status DMA register initialization */
#ifdef FLEXIO0_TIMERSDEN_INIT
  FLEXIO0->TIMERSDEN = FLEXIO0_TIMERSDEN_INIT;
#else
  FLEXIO0->TIMERSDEN = 0x0U;
#endif /* FLEXIO0_TIMERSDEN_INIT */
#endif /* FLEXIO_TIMERSDEN_TSDE_MASK */

#ifdef FLEXIO_SHIFTSTATE_STATE_MASK
  /* Shifter state register initialization */
#ifdef FLEXIO0_SHIFTSTATE_INIT
  FLEXIO0->SHIFTSTATE = FLEXIO0_SHIFTSTATE_INIT;
#else
  FLEXIO0->SHIFTSTATE = 0x0U;
#endif /* FLEXIO0_SHIFTSTATE_INIT */
#endif /* FLEXIO_SHIFTSTATE_STATE_MASK */

#ifdef FLEXIO_TRIGIEN_TRIE_MASK
  /* Trigger interrupt enable register initialization */
#ifdef FLEXIO0_TRIGIEN_INIT
  FLEXIO0->TRIGIEN = FLEXIO0_TRIGIEN_INIT;
#else
  FLEXIO0->TRIGIEN = 0x0U;
#endif /* FLEXIO0_TRIGIEN_INIT */
#endif /* FLEXIO_TRIGIEN_TRIE_MASK */

#ifdef FLEXIO_PINIEN_PSIE_MASK
  /* Pin interrupt enable register */
#ifdef FLEXIO0_PINIEN_INIT
  FLEXIO0->PINIEN = FLEXIO0_PINIEN_INIT;
#else
  FLEXIO0->PINIEN = 0x0U;
#endif /* FLEXIO0_PINIEN_INIT */
#endif /* FLEXIO_PINIEN_PSIE_MASK */

#ifdef FLEXIO_PINREN_PRE_MASK
  /* Pin rising edge enable register initialization */
#ifdef FLEXIO0_PINREN_INIT
  FLEXIO0->PINREN = FLEXIO0_PINREN_INIT;
#else
  FLEXIO0->PINREN = 0x0U;
#endif /* FLEXIO0_PINREN_INIT */
#endif /* FLEXIO_PINREN_PRE_MASK */

#ifdef FLEXIO_PINFEN_PFE_MASK
  /* Pin falling edge enable register initialization */
#ifdef FLEXIO0_PINFEN_INIT
  FLEXIO0->PINFEN = FLEXIO0_PINFEN_INIT;
#else
  FLEXIO0->PINFEN = 0x0U;
#endif /* FLEXIO0_PINFEN_INIT */
#endif /* FLEXIO_PINFEN_PFE_MASK */

#ifdef FLEXIO_PINOUTE_OUTE_MASK
  /* Pin output enable register initialization */
#ifdef FLEXIO0_PINOUTE_INIT
  FLEXIO0->PINOUTE = FLEXIO0_PINOUTE_INIT;
#else
  FLEXIO0->PINOUTE = 0x0U;
#endif /* FLEXIO0_PINOUTE_INIT */
#endif /* FLEXIO_PINOUTE_OUTE_MASK */

#ifdef FLEXIO_PINOUTD_OUTD_MASK
  /* Pin output register initialization */
#ifdef FLEXIO0_PINOUTD_INIT
  FLEXIO0->PINOUTD = FLEXIO0_PINOUTD_INIT;
#else
  FLEXIO0->PINOUTD = 0x0U;
#endif /* FLEXIO0_PINOUTD_INIT */
#endif /* FLEXIO_PINOUTD_OUTD_MASK */

#ifdef FLEXIO0_CTRL_INIT
  FLEXIO0->CTRL = (FLEXIO0_CTRL_INIT & ~FLEXIO_CTRL_SWRST_MASK);
#else
  FLEXIO0->CTRL = 0x0U;
#endif /* FLEXIO0_CTRL_INIT */
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPreInit(void)
{
  /* Enable clock gate of the FLEXIO0 peripheral. */
  SYSCON0->AHBCLKCTRL2 |= SYSCON_AHBCLKCTRL2_FLEXIO_MASK;
}

void BOARD_InitPeripherals(void)
{
  /* Common pre-initialization */
  BOARD_InitPeripherals_CommonPreInit();
  /* Initialize components */
  FLEXIO0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
