/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* FLEXIO0_CTRL: DOZEN=0, DBGE=1, FASTACC=0, FLEXEN=1 */
#define FLEXIO0_CTRL_INIT 0x40000001U
/* FLEXIO0_SHIFTSIEN: SSIE=0 */
#define FLEXIO0_SHIFTSIEN_INIT 0x0U
/* FLEXIO0_SHIFTEIEN: SEIE=0 */
#define FLEXIO0_SHIFTEIEN_INIT 0x0U
/* FLEXIO0_TIMIEN: TEIE=0 */
#define FLEXIO0_TIMIEN_INIT 0x0U
/* FLEXIO0_SHIFTSDEN: SSDE=0 */
#define FLEXIO0_SHIFTSDEN_INIT 0x0U
/* FLEXIO0_TIMERSDEN: TSDE=0 */
#define FLEXIO0_TIMERSDEN_INIT 0x0U
/* FLEXIO0_SHIFTSTATE: STATE=0 */
#define FLEXIO0_SHIFTSTATE_INIT 0x0U
/* FLEXIO0_TRIGIEN: TRIE=0 */
#define FLEXIO0_TRIGIEN_INIT 0x0U
/* FLEXIO0_PINIEN: PSIE=0 */
#define FLEXIO0_PINIEN_INIT 0x0U
/* FLEXIO0_PINREN: PRE=0 */
#define FLEXIO0_PINREN_INIT 0x0U
/* FLEXIO0_PINFEN: PFE=0 */
#define FLEXIO0_PINFEN_INIT 0x0U
/* FLEXIO0_PINOUTD: OUTD=0 */
#define FLEXIO0_PINOUTD_INIT 0x0U
/* FLEXIO0_PINOUTE: OUTE=0 */
#define FLEXIO0_PINOUTE_INIT 0x0U
/* FLEXIO0_SHIFTCTL0: TIMSEL=0, TIMPOL=0, PINCFG=3, PINSEL=16, PINPOL=0, SMOD=6 */
#define FLEXIO0_SHIFTCTL0_INIT 0x31006U
/* FLEXIO0_SHIFTCTL1: TIMSEL=1, TIMPOL=0, PINCFG=3, PINSEL=16, PINPOL=0, SMOD=6 */
#define FLEXIO0_SHIFTCTL1_INIT 0x1031006U
/* FLEXIO0_SHIFTCTL2: TIMSEL=2, TIMPOL=0, PINCFG=3, PINSEL=16, PINPOL=0, SMOD=6 */
#define FLEXIO0_SHIFTCTL2_INIT 0x2031006U
/* FLEXIO0_SHIFTCTL3: TIMSEL=3, TIMPOL=0, PINCFG=3, PINSEL=16, PINPOL=0, SMOD=6 */
#define FLEXIO0_SHIFTCTL3_INIT 0x3031006U
/* FLEXIO0_SHIFTCTL4: TIMSEL=4, TIMPOL=0, PINCFG=3, PINSEL=16, PINPOL=0, SMOD=6 */
#define FLEXIO0_SHIFTCTL4_INIT 0x4031006U
/* FLEXIO0_SHIFTCFG0: PWIDTH=15, SSIZE=0, LATST=0, INSRC=0, SSTOP=3, SSTART=0 */
#define FLEXIO0_SHIFTCFG0_INIT 0xF0030U
/* FLEXIO0_SHIFTCFG1: PWIDTH=15, SSIZE=0, LATST=0, INSRC=0, SSTOP=3, SSTART=0 */
#define FLEXIO0_SHIFTCFG1_INIT 0xF0030U
/* FLEXIO0_SHIFTCFG2: PWIDTH=15, SSIZE=0, LATST=0, INSRC=0, SSTOP=3, SSTART=0 */
#define FLEXIO0_SHIFTCFG2_INIT 0xF0030U
/* FLEXIO0_SHIFTCFG3: PWIDTH=15, SSIZE=0, LATST=0, INSRC=0, SSTOP=3, SSTART=0 */
#define FLEXIO0_SHIFTCFG3_INIT 0xF0030U
/* FLEXIO0_SHIFTCFG4: PWIDTH=15, SSIZE=0, LATST=0, INSRC=0, SSTOP=3, SSTART=0 */
#define FLEXIO0_SHIFTCFG4_INIT 0xF0030U
/* FLEXIO0_SHIFTBUF0: SHIFTBUF=33554433 */
#define FLEXIO0_SHIFTBUF0_INIT 0x2000001U
/* FLEXIO0_SHIFTBUF1: SHIFTBUF=2 */
#define FLEXIO0_SHIFTBUF1_INIT 0x2U
/* FLEXIO0_SHIFTBUF2: SHIFTBUF=16777219 */
#define FLEXIO0_SHIFTBUF2_INIT 0x1000003U
/* FLEXIO0_SHIFTBUF3: SHIFTBUF=4 */
#define FLEXIO0_SHIFTBUF3_INIT 0x4U
/* FLEXIO0_SHIFTBUF4: SHIFTBUF=33554432 */
#define FLEXIO0_SHIFTBUF4_INIT 0x2000000U
/* FLEXIO0_TIMCTL0: TRGSEL=19, TRGPOL=0, TRGSRC=1, PINCFG=3, PINSEL=24, PINPOL=0, PININS=0, ONETIM=0, TIMOD=3 */
#define FLEXIO0_TIMCTL0_INIT 0x13431803U
/* FLEXIO0_TIMCTL1: TRGSEL=2, TRGPOL=1, TRGSRC=1, PINCFG=3, PINSEL=25, PINPOL=0, PININS=0, ONETIM=0, TIMOD=3 */
#define FLEXIO0_TIMCTL1_INIT 0x2C31903U
/* FLEXIO0_TIMCTL2: TRGSEL=19, TRGPOL=1, TRGSRC=1, PINCFG=3, PINSEL=26, PINPOL=0, PININS=0, ONETIM=0, TIMOD=3 */
#define FLEXIO0_TIMCTL2_INIT 0x13C31A03U
/* FLEXIO0_TIMCTL3: TRGSEL=0, TRGPOL=1, TRGSRC=1, PINCFG=3, PINSEL=27, PINPOL=0, PININS=0, ONETIM=0, TIMOD=3 */
#define FLEXIO0_TIMCTL3_INIT 0xC31B03U
/* FLEXIO0_TIMCTL4: TRGSEL=0, TRGPOL=0, TRGSRC=0, PINCFG=3, PINSEL=28, PINPOL=0, PININS=0, ONETIM=0, TIMOD=3 */
#define FLEXIO0_TIMCTL4_INIT 0x31C03U
/* FLEXIO0_TIMCFG0: TIMOUT=1, TIMDEC=0, TIMRST=0, TIMDIS=6, TIMENA=6, TSTOP=0, TSTART=0 */
#define FLEXIO0_TIMCFG0_INIT 0x1006600U
/* FLEXIO0_TIMCFG1: TIMOUT=1, TIMDEC=0, TIMRST=0, TIMDIS=6, TIMENA=6, TSTOP=0, TSTART=0 */
#define FLEXIO0_TIMCFG1_INIT 0x1006600U
/* FLEXIO0_TIMCFG2: TIMOUT=1, TIMDEC=0, TIMRST=0, TIMDIS=6, TIMENA=6, TSTOP=0, TSTART=0 */
#define FLEXIO0_TIMCFG2_INIT 0x1006600U
/* FLEXIO0_TIMCFG3: TIMOUT=1, TIMDEC=0, TIMRST=0, TIMDIS=6, TIMENA=6, TSTOP=0, TSTART=0 */
#define FLEXIO0_TIMCFG3_INIT 0x1006600U
/* FLEXIO0_TIMCFG4: TIMOUT=0, TIMDEC=0, TIMRST=0, TIMDIS=0, TIMENA=0, TSTOP=0, TSTART=0 */
#define FLEXIO0_TIMCFG4_INIT 0x0U
/* FLEXIO0_TIMCMP0: CMP=49 */
#define FLEXIO0_TIMCMP0_INIT 0x31U
/* FLEXIO0_TIMCMP1: CMP=4 */
#define FLEXIO0_TIMCMP1_INIT 0x4U
/* FLEXIO0_TIMCMP2: CMP=149 */
#define FLEXIO0_TIMCMP2_INIT 0x95U
/* FLEXIO0_TIMCMP3: CMP=4 */
#define FLEXIO0_TIMCMP3_INIT 0x4U
/* FLEXIO0_TIMCMP4: CMP=199 */
#define FLEXIO0_TIMCMP4_INIT 0xC7U

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
